### ISSUE TITLE
开放科学系综

### ISSUE THREAD

**Issue by emptymalei** [kausalflow/openscience#2]
open science ensemble

考虑到现在科研过程的重现和保存简直是一团糟，我们可以讨论一个比好的用来完整的保存、传递、分享、追踪一个科研项目的协议。

目前现在比较热门的关于 data protocol 的项目是 [data protocols](http://dataprotocols.org/data-packages/)，这个项目里面在讨论一种关于如何存放数据的 protocol.

他们基本的想法是一个完整的 data package 应该至少包含两部分
1. 数据
2. 描述

另外还可以选择性的有其他辅助性的内容，例如用来处理数据的程序、参考文献等等。

这是一个 package，我们现在需要一个更加大的体系，出来本项目的所有的内容，应该还可以帮助大家更加容易的找到与此项目相关的其他的项目，所有我暂时起名叫做系综（ensemble）了。

那么仿照 data protocol 的内容，我自己的想法是：
1. 一个 open science ensemble (ose) 应该包括项目的说明文件 osensemble.json （可以有子说明），项目的过程记录，项目的结果部分（包括初步结果），项目工具，项目参考过的内容，及其他。
2. osensemble.json 文件应该描述清楚这个 ose 的内容（包括目录结构和每个目录的内容简介），版本记录，分支记录，参与者，链接等等。此文件必须放置在 ose 的最顶级目录。
3. 项目的过程记录（project）可以包括：
   a. 思路：研究的思路
   b. 方法：方法的一些描述
   c. 数据：数据的类型可以任意但是需要在 osensemble.json 中说明类型
   c. 推导：理论推导过程
4. 项目的结果（results）：结论的记录，发表的文章，实际的应用，获得产品等等。
5. 项目的工具（tools）：例如数据处理的程序。不一定非要开源或者附上代码，可以对工具进行描述，至少方便其他人重复。
6. 项目的参考（references）：参考文献等等
7. 其他：自定义内容。可以有多个自定义内容，例如 ose_acknowledgement ，例如 ose_whatever。但是这些自定义需要在 osensemble.json 中声明，在这些目录下面也应该有相应的解释等等。

**关于如何把与这个相关的项目关联起来，我并没有好的想法，难道仅仅是通过添加一个 connect.json 来描述这个项目与其他项目的关系？略简单了些。**

**另外我觉得类似 github 的 fork 这种也应该用起来，这样可以方便别人获取并且在原来工作的基础上检查、改进或者进一步的研究。这样可以形成一个 类似 github 的 network 图，可以跟踪跟这个项目相关的其他的工作。这样才可以把 package 链接起来，形成 ensemble.**

可以以我们这个open science 项目为例做一个放在 master branch 的 osensemble 目录下面。

或者如果大家觉得这里面的名字起得很奇特，可以换更好的名字，名字什么的，不重要。

**Comment by unionx** [comment]
看看这个项目，不知道是不是类似的想法：[Open Science Framework](https://osf.io/)

**Comment by emptymalei** [comment]
@unionx 我们的 wiki 页面有收集他（https://github.com/GuokrUnion/openscience/wiki ）。我在用，还不够好。

不过话说他们年前拿到了一大笔一大笔的钱，够他们折腾了。

**Comment by unionx** [comment]
@emptymalei 嗯嗯，还有这个：[科学工作者的编程指南](http://software-carpentry.org/index.html)

**Comment by emptymalei** [comment]
@unionx 这个有意思。我去研究研究~ 话说一个最简单的方法是在 那个 [data protocol](http://dataprotocols.org/data-packages/) 上面修改，毕竟不过文档还是什么的都可以看成 data 嘛。

**Comment by unionx** [comment]
@emptymalei 总之我觉得现在的科学工作者都应该有基础的编程技能，以便协作。好消息是，我的很多朋友都开始学习Git和Python这些东西了。

**Comment by emptymalei** [comment]
@unionx Git 这类是必备的，在我的推广下，我系有部分学生开始用了。即便不是写程序，git 也非常重要，现在感觉这理念应该直接成为操作系统的一部分。

**Comment by emptymalei** [comment]
@unionx 还有没有什么其他的 CS 的东西可以用在其他的科学工作里面的啊~

**Comment by unionx** [comment]
@emptymalei 出了某些任何领域都需要的，直接处理数据的工具，其他的就是分学科的软件了吧。这个可以罗列一下，写一个wiki。

**Comment by emptymalei** [comment]
生成了一个例子。先关掉这个 issue 了。以后需要再开。
