### ISSUE TITLE
Open Science Framework 跟踪

### ISSUE THREAD

**Issue by emptymalei** [kausalflow/openscience#7]
专门加一个 issue 来跟踪 osf 的情况。

文件管理改进
![image](https://f.cloud.github.com/assets/663798/2527615/db66a568-b506-11e3-8f22-518615e53ffd.png)

添加了统计功能
![image](https://f.cloud.github.com/assets/663798/2527607/c810dad8-b506-11e3-8fd1-6645e5522ebc.png)

**Comment by i2000s** [comment]
OSF项目内的Sara允许我转播了两个介绍性的视频到youku，今后OSF的视频均将以Creative Commons by Attribution协议发布。希望@emptymalei能继续跟进，并搜集更多这类资源。感谢你的贡献！

两个OSF webinar的视频连接：
http://v.youku.com/v_show/id_XMTQ2NzEzODUzMg==.html
http://v.youku.com/v_show/id_XMTQ2NzEzODUyOA==.html
